### ISSUE TITLE
Why schelm?

### ISSUE THREAD

**Issue by ChristianWeissCG** [databus23/schelm#2]
Is see no difference between `schelm -f OUTPUT_DIR < manifest.txt` and `helm template --output-dir OUTPUT_DIR_TEMPLATE path/to/mychart/`.

The only thing i can spot is a generated release name vs static text:`RELEASE_NAME`.

In which situations is schelm adding a benefit?

**Comment by databus23** [comment]
Schelm predates `helm template`. It was superseeded by it.
